### PR TITLE
fix: move header error out of enum

### PR DESCRIPTION
**Pull request by fontanierh**
Remove the Invalid Response Header out of the enum

### CODE REVIEW

**Review by spolu — APPROVED** [review]
LGTM

why std::result::Result given the fact that the file has `pub type Result<T> = std::result::Result<T, Error>;`  ?

I would move it next to ResponseWrapper but otherwise LGTM

**Comment by fontanierh** [comment]
> why std::result::Result given the fact that the file has pub type Result<T> = std::result::Result<T, Error>; ?

Precisely because we're not returning `Error`, which is the `Enum` defined in this file that has the SSE loop errors.

**Comment by fontanierh** [comment]
> I would move it next to ResponseWrapper but otherwise LGTM

Can def do that 👍

**Comment by spolu** [comment]
> > why std::result::Result given the fact that the file has pub type Result = std::result::Result<T, Error>; ?
> 
> Precisely because we're not returning `Error`, which is the `Enum` defined in this file that has the SSE loop errors.

Ah I see :+1:

**Pull request merged**
